### ISSUE TITLE
Change CSS code like follows

### ISSUE THREAD

**Issue by Tharindu37** [Navodi99/Hotello#1]
```CSS
#showcase{
    /* min-height: 1000px; */
    background: url('images/Untitled-design-1-1.webp') no-repeat;
    background-size: cover;
    text-align: center;
    color: #ffffff;
    display: flex;
    flex-direction: column;
    align-items: center;
    height: 90vh;
}
```
