### ISSUE TITLE
Change HTML & CSS code like follows

### ISSUE THREAD

**Issue by Tharindu37** [Navodi99/Hotello#2]
https://github.com/Navodi99/Hotello/blob/48a3cef67d9b26363d5571259da8f92f98d62857/index.html#L56-L81
Change above HTML code like follows
```HTML
<div class="list"  style="width: 25%;"> 
     <form class="form"> 
         <select style="padding: 20px;" class="items" name="Guests" id="Guest-no"> 
              
             <option selected disabled hidden value="volvo">Guest</option> 
             <option value="saab">1</option> 
             <option value="opel">2</option> 
             <option value="audi">3</option> 
             <option value="audi">4</option> 
             <option value="audi">5</option> 
           </select> 
     </form> 
 </div> 
 <div class="list"  style="width: 25%;"> 
     <form class="form"> 
         <select style="padding: 20px;" class="items" name="children" id="children-no"> 
             <option value="volvo">Children</option> 
             <option value="saab">1</option> 
             <option value="opel">2</option> 
             <option value="audi">3</option> 
             <option value="audi">4</option> 
             <option value="audi">5</option> 
           </select> 
     </form> 
 </div> 
 <div  style="width: 25%;" class="list" > 
```
Change CSS code like follows
```CSS
.lists {
    margin-top: 100px;
    overflow: hidden;
    display: flex;
    width: 80%;
    background-color: #ffffff;
    justify-content: space-between;

}
```
